### ISSUE TITLE
Should be server side

### ISSUE THREAD

**Issue by SettingDust** [P03W/headshot#2]
Due to description, it's server only mod.
https://github.com/P03W/headshot/blob/master/src/main/resources/fabric.mod.json#L11 should be `server`

**Comment by SilverAndro** [comment]
Last I checked that made it not load at all in single player though

**Comment by SilverAndro** [comment]
Yep just checked the [spec](https://fabricmc.net/wiki/documentation:fabric_mod_json_spec) and it wont load in singleplayer

> “server” - the game dedicated server (integrated servers are not included here)

Wont "fix"/change
